In [15]:
import pandas as pd
import statsmodels.formula.api as smf
import numpy as np

# Question 1

In [4]:
titanic = pd.read_csv('titanic.csv.bz2')

In [5]:
titanic.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [7]:
titanic.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

# Question 2

In [55]:
model = smf.ols(formula='survived~C(pclass)+sex',data=titanic)
model = model.fit()
model_summary = model.summary()

In [56]:
print(model_summary)

                            OLS Regression Results                            
Dep. Variable:               survived   R-squared:                       0.341
Model:                            OLS   Adj. R-squared:                  0.340
Method:                 Least Squares   F-statistic:                     225.5
Date:                Wed, 11 Apr 2018   Prob (F-statistic):          7.79e-118
Time:                        19:57:01   Log-Likelihood:                -639.22
No. Observations:                1309   AIC:                             1286.
Df Residuals:                    1305   BIC:                             1307.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.8990      0.025     35.

# Question 3

In [38]:
survived_hat = r.predict()
print(survived_hat)

[0.89898393 0.39411348 0.89898393 ... 0.10147811 0.10147811 0.10147811]


# Question 4

In [39]:
min(survived_hat)

0.10147811470358525

In [40]:
max(survived_hat)

0.8989839322447712

# Question 5

In [46]:
survived_hat = (r.predict() > 0.5) + 0
print(survived_hat)


[1 0 1 ... 0 0 0]


# Question 6

In [47]:
from sklearn.metrics import accuracy_score

In [73]:
a = accuracy_score(titanic.survived,survived_hat)
print(a)

0.7799847211611918


# Question 7

In [60]:
model1 = smf.ols(formula='survived~C(pclass)*sex',data=titanic)

In [61]:
model1 = model1.fit()

In [62]:
model1_summary = model1.summary()
print(model1_summary)

                            OLS Regression Results                            
Dep. Variable:               survived   R-squared:                       0.370
Model:                            OLS   Adj. R-squared:                  0.368
Method:                 Least Squares   F-statistic:                     153.2
Date:                Wed, 11 Apr 2018   Prob (F-statistic):          4.02e-128
Time:                        19:58:57   Log-Likelihood:                -609.86
No. Observations:                1309   AIC:                             1232.
Df Residuals:                    1303   BIC:                             1263.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept           

# Question 8

96% people survived if they were in class 1 and were female.
89% people survived if they were in class 2 and were female.
49% people survived if they were in class 3 and were female.
34% people survived if they were in class 1 and were male.

# Question 9

In [69]:
survived_hat1 = model1.predict()
print(survived_hat1)

[0.96527778 0.34078212 0.96527778 ... 0.15212982 0.15212982 0.15212982]


In [70]:
survived_hat1 = (survived_hat1 > 0.5) + 0

In [75]:
b = accuracy_score(titanic.survived,survived_hat1)
print(b)

0.7830404889228418


In [76]:
b - a

0.0030557677616500634

accuracy improved by 0.3%